# This is the GITHUB URL where Kubernetes manifests are stored.
# If you forked this repo, you will need to update this.
repo_url: "https://github.com/livewyer-ops/cnoe-reference-implementation-azure.git"
# Tags to apply to Azure resources
tags:
  env: "dev"
  project: "cnoe"
region: "eastus"
# The name of the resource group you are installing this under.
resource_group: cnoe-idp
# The name of the AKS cluster you are installing this under.
cluster_name: cnoe-idp
# Set this to false if you want to manage DNS somewhere else. e.g. manually.
enable_dns_management: true
# If using external DNS, specify the Azure DNS hosted zone ID. Required if enable_dns_management is set to true
dns_zone_id: /subscriptions/<SUBSCRIPTION_ID>/resourceGroups/<RESOURCE_GROUP>/providers/Microsoft.Network/dnszones/<ZONE_NAME>
domain_name: sudbomain.domain.root
# If set to true, we will store secrets to Azure Secrets Manager, then sync it to the cluster using External Secrets Operator.
enable_external_secret: true
