apiVersion: azure.livewyer.io/v1alpha1
kind: WorkloadIdentity
metadata:
  name: external-dns
  namespace: external-dns
spec:
  forProvider:
    location: "{{ .location }}"
    oidcIssuerURL: "{{ .clusterOIDCIssuerURL }}"
    resourceGroupName: "{{ .resourceGroup }}"
    roleAssignments:
      - roleDefinitionName: DNS Zone Contributor
        scope: "{{ .subscription }}"
      - roleDefinitionName: Reader
        scope: "{{ .subscription }}"
    serviceAccountName: external-dns

---
apiVersion: azure.livewyer.io/v1alpha1
kind: WorkloadIdentity
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  forProvider:
    location: "{{ .location }}"
    oidcIssuerURL: "{{ .clusterOIDCIssuerURL }}"
    resourceGroupName: "{{ .resourceGroup }}"
    roleAssignments:
      - roleDefinitionName: Key Vault Secrets User
        scope: "{{ .subscription }}/resourcegroups/resource-{{ .resourceGroup }}"
    serviceAccountName: external-secrets

---
apiVersion: azure.livewyer.io/v1alpha1
kind: WorkloadIdentity
metadata:
  name: keycloak
  namespace: keycloak
spec:
  forProvider:
    location: "{{ .location }}"
    oidcIssuerURL: "{{ .clusterOIDCIssuerURL }}"
    resourceGroupName: "{{ .resourceGroup }}"
    roleAssignments:
      - roleDefinitionName: Key Vault Secrets User
        scope: "{{ .subscription }}"
      - roleDefinitionName: Key Vault Reader
        scope: "{{ .subscription }}"
    serviceAccountName: external-secret-keycloak
