helmDefaults:
  cleanupOnFail: true
  createNamespace: true
  wait: true

repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm
  - name: crossplane
    url: https://charts.upbound.io/stable

releases:
  - name: argocd
    namespace: argocd
    chart: argo/argo-cd
    version: '{{ ((readFile (printf "%s/%s" (requiredEnv "REPO_ROOT") "packages/addons/values.yaml")) | fromYaml).argocd.defaultVersion }}'
    values:
      - packages/bootstrap/argocd.yaml.gotmpl
    suppressDiff: true
  - name: cnoe-seed-appset
    namespace: argocd
    chart: packages/charts/appset
    values:
      - packages/bootstrap/seed-addons.yaml
    disableValidationOnInstall: true
    suppressDiff: true
    needs:
      - argocd/argocd
