helmDefaults:
  cleanupOnFail: true
  createNamespace: true
  wait: true

repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm
  - name: crossplane
    url: https://charts.upbound.io/stable

releases:
  - name: argocd
    namespace: argocd
    chart: argo/argo-cd
    version: '{{ ((readFile (printf "%s/%s" (requiredEnv "REPO_ROOT") "packages/addons/values.yaml")) | fromYaml).argocd.defaultVersion }}'
    values:
      - packages/argo-cd/values.yaml
      - packages/argo-cd/values.yaml.gotmpl
  # - name: crossplane
  #   namespace: crossplane-system
  #   chart: crossplane/crossplane
  #   version: '{{ ((readFile (printf "%s/%s" (requiredEnv "REPO_ROOT") "packages/addons/values.yaml")) | fromYaml).crossplane.defaultVersion }}'
  #   values:
  #     - packages/crossplane/values.yaml
  #   disableValidationOnInstall: true
  - name: cnoe-argocd-config
    namespace: argocd
    chart: packages/charts/raw
    values:
      - packages/bootstrap/argocd.yaml.gotmpl
    disableValidationOnInstall: true
    needs:
      - argocd/argocd
  # - name: cnoe-crossplane-addon-providers
  #   namespace: crossplane-system
  #   chart: packages/charts/raw
  #   values:
  #     - packages/bootstrap/crossplane-providers.yaml.gotmpl
  #   disableValidationOnInstall: true
  #   needs:
  #     - crossplane-system/crossplane
  # - name: cnoe-crossplane-addon-functions
  #   namespace: crossplane-system
  #   chart: packages/charts/raw
  #   values:
  #     - packages/bootstrap/crossplane-functions.yaml.gotmpl
  #   disableValidationOnInstall: true
  #   needs:
  #     - crossplane-system/crossplane
  # - name: cnoe-crossplane-addon-configurations
  #   namespace: crossplane-system
  #   chart: packages/charts/raw
  #   values:
  #     - packages/bootstrap/crossplane-configurations.yaml.gotmpl
  #   disableValidationOnInstall: true
  #   needs:
  #     - crossplane-system/crossplane
  #     - crossplane-system/cnoe-crossplane-addon-providers
  #     - crossplane-system/cnoe-crossplane-addon-functions
  # - name: cnoe-crossplane-addon-config
  #   namespace: crossplane-system
  #   chart: packages/charts/raw
  #   values:
  #     - packages/bootstrap/crossplane-clusterproviderconfig.yaml.gotmpl
  #   disableValidationOnInstall: true
  #   needs:
  #     - crossplane-system/crossplane
  #     - crossplane-system/cnoe-crossplane-addon-providers
  - name: cnoe-appset
    namespace: argocd
    chart: packages/charts/appset
    values:
      - packages/addons/values.yaml
    disableValidationOnInstall: true
    needs:
      - argocd/cnoe-argocd-config
      # - crossplane-system/cnoe-crossplane-addon-configurations
      # - crossplane-system/cnoe-crossplane-addon-config
