# https://taskfile.dev

version: "3"

env:
  KUBECONFIG:
    sh: mktemp
  REPO_ROOT:
    sh: git rev-parse --show-toplevel

tasks:
  init:
    deps:
      - update:kubeconfig
    cmds:
      - defer: { task: cleanup }
      - task: helmfile:init
      - task: helmfile:lint
      - task: helmfile:build

  install:
    deps:
      - update:kubeconfig
    cmds:
      - defer: { task: cleanup }
      - task: helmfile:apply
      - task: update:secret

  update:
    deps:
      - update:kubeconfig
    cmds:
      - defer: { task: cleanup }
      - task: helmfile:sync
      - task: update:secret

  update:secret:
    preconditions:
      - test -f private/azure-credentials.yaml
    cmds:
      - kubectl apply -f private/azure-credentials.yaml

  update:kubeconfig:
    preconditions:
      - test -f config.yaml
    cmds:
      - az aks get-credentials --name $(yq '.cluster_name' config.yaml) --resource-group $(yq '.resource_group' config.yaml) --file "{{.KUBECONFIG}}"

  cleanup:
    internal: true
    cmds:
      - rm -f "{{.KUBECONFIG}}"

  uninstall:
    deps:
      - update:kubeconfig
    cmds:
      - defer: { task: cleanup }
      - task: update:kubeconfig
      - task: helmfile:destroy

  helmfile:init:
    cmds:
      - helmfile init {{.CLI_ARGS}}
  helmfile:lint:
    cmds:
      - helmfile lint {{.CLI_ARGS}}
  helmfile:diff:
    cmds:
      - helmfile diff {{.CLI_ARGS}}
  helmfile:build:
    cmds:
      - helmfile build {{.CLI_ARGS}}
  helmfile:apply:
    cmds:
      - helmfile apply {{.CLI_ARGS}}
  helmfile:list:
    cmds:
      - helmfile list {{.CLI_ARGS}}
  helmfile:status:
    cmds:
      - helmfile status {{.CLI_ARGS}}
  helmfile:template:
    cmds:
      - helmfile template {{.CLI_ARGS}}
  helmfile:deps:
    cmds:
      - helmfile deps {{.CLI_ARGS}}
  helmfile:sync:
    cmds:
      - helmfile sync {{.CLI_ARGS}}
  helmfile:destroy:
    cmds:
      - helmfile destroy {{.CLI_ARGS}}
