# https://taskfile.dev

version: "3"

set: [errexit, nounset, pipefail]

env:
  KUBECONFIG: "{{.ROOT_DIR}}/private/kubeconfig"
  REPO_ROOT: "{{.ROOT_DIR}}"
  KEYVAULT_NAME:
    sh: yq '.keyvault // "cnoe-ref-impl"' config.yaml

tasks:
  init:
    deps:
      - update:kubeconfig
    cmds:
      - defer: { task: cleanup }
      - task: helmfile:init
      - task: helmfile:lint
      - task: helmfile:build

  install:
    deps:
      - update:kubeconfig
    cmds:
      - defer: { task: cleanup }
      - task: azure:creds
      - task: helmfile
      - task: update

  diff:
    deps:
      - update:kubeconfig
    cmds:
      - defer: { task: cleanup }
      - task: helmfile:diff

  sync:
    deps:
      - update:kubeconfig
    cmds:
      - defer: { task: cleanup }
      - task: helmfile:sync
      - task: update

  update:
    deps:
      - task: update:kubeconfig
        silent: true
    cmds:
      - defer: { task: cleanup }
      - task: update:crossplane
      - task: update:secret

  update:secret:
    deps:
      - task: update:kubeconfig
        silent: true
    vars:
      RESOURCE_GROUP:
        sh: yq '.resource_group' config.yaml
    cmds:
      - defer: { task: cleanup }
      - task: update:secret:azure
      - task: wait
        vars:
          IF: $(kubectl get ns | grep external-dns | wc -l) -eq 0
      - task: wait
        vars:
          IF: $(az identity show --resource-group "{{.RESOURCE_GROUP}}" --name external-dns --only-show-errors 2>/dev/null | wc -l) -eq 0
      - task: update:secret:external-dns

  # NOTE: THIS IS NOT IDEAL
  # TODO: move this task to manifest or use other method to manage
  update:secret:external-dns:
    deps:
      - task: update:kubeconfig
        silent: true
      - task: azure:init
        silent: true
    preconditions:
      - yq 'true' config.yaml
    vars:
      SUBSCRIPTION_ID:
        sh: yq '.subscription' config.yaml
      RESOURCE_GROUP:
        sh: yq '.resource_group' config.yaml
      TENANT_ID:
        sh: az identity show --resource-group "{{.RESOURCE_GROUP}}" --name external-dns --query "tenantId" --output tsv --only-show-errors
      CLIENT_ID:
        sh: az identity show --resource-group "{{.RESOURCE_GROUP}}" --name external-dns --query "clientId" --output tsv --only-show-errors
      SECRET_TEMP:
        sh: mktemp
    sources:
      - config.yaml
    generates:
      - "{{.SECRET_TEMP}}"
    cmds:
      - defer: rm -f {{.SECRET_TEMP}}
      - cmd: yq --null-input -o=json '.aadClientId = "{{.CLIENT_ID}}" | .tenantId = "{{.TENANT_ID}}" | .subscriptionId = "{{.SUBSCRIPTION_ID}}" | .resourceGroup = "{{.RESOURCE_GROUP}}" | .useWorkloadIdentityExtension = true' > {{.SECRET_TEMP}}
      - kubectl create secret generic external-dns-azure --namespace external-dns --from-file='azure.json'={{.SECRET_TEMP}}

  update:secret:azure:
    deps:
      - task: azure:init
        silent: true
    preconditions:
      - yq 'true' config.yaml
    vars:
      TAGS:
        sh: yq eval '.tags | to_entries | map(.key + "=" + .value) | join(" ")' config.yaml
      SECRET_TEMP:
        sh: mktemp
      KUBELET_IDENTITY_OBJECT_ID:
        sh: az aks show --name $(yq '.cluster_name' config.yaml) --resource-group $(yq '.resource_group' config.yaml) --query 'identityProfile.kubeletidentity.objectId' -o tsv --only-show-errors
    sources:
      - config.yaml
    generates:
      - "{{.SECRET_TEMP}}"
    cmds:
      - task: if
        vars:
          IF: $(az keyvault list -o yaml --only-show-errors | KEYVAULT_NAME=${KEYVAULT_NAME} yq '.[] | [select(.name==env(KEYVAULT_NAME))] | length') -eq 0
          RUN: az keyvault create --resource-group $(yq '.resource_group' config.yaml) --enable-rbac-authorization --tags {{.TAGS}} ${KEYVAULT_NAME} --only-show-errors
      - defer: rm -f {{.SECRET_TEMP}}
      - yq -o=json config.yaml > {{.SECRET_TEMP}}
      - |
        az keyvault secret set \
          --name config \
          --vault-name ${KEYVAULT_NAME} \
          --file {{.SECRET_TEMP}} \
          --description "Secret for config of CNOE Azure Reference Implementation" \
          --tags {{.TAGS}} \
          --only-show-errors --output yaml | yq 'del(.value)'

  update:crossplane:
    deps:
      - task: update:kubeconfig
        silent: true
    cmds:
      - defer: { task: cleanup }
      - task: wait
        vars:
          IF: $(kubectl get provider.pkg.crossplane.io -o yaml 2>/dev/null | yq '[.items[] | select(.metadata.name=="*provider-kubernetes")] | length') -eq 0
      - task: wait
        vars:
          IF: $(kubectl -n crossplane-system get sa -o name | grep provider-kubernetes | wc -l) -eq 0
      - task: if
        vars:
          IF: $(kubectl get clusterrolebindings -o yaml | yq '[.items[] | select(.metadata.name=="provider-kubernetes-admin-binding")] | length') -eq 0
          RUN: kubectl create clusterrolebinding provider-kubernetes-admin-binding --clusterrole cluster-admin --serviceaccount="$(kubectl -n crossplane-system get sa -o yaml | yq '.items[] | select(.metadata.name=="*provider-kubernetes*") | [.metadata.namespace, .metadata.name] | join(":")')"

  update:kubeconfig:
    deps:
      - task: azure:init
        silent: true
    preconditions:
      - yq 'true' config.yaml
    cmds:
      - az aks get-credentials --name $(yq '.cluster_name' config.yaml) --resource-group $(yq '.resource_group' config.yaml) --overwrite-existing --only-show-errors

  update:config:
    internal: true
    cmd: |-
      {{.RUN}}

  azure:init:
    preconditions:
      - yq 'true' config.yaml
    vars:
      SUBSCRIPTION_ID:
        sh: yq '.subscription' config.yaml
    cmds:
      - az account set --subscription "{{.SUBSCRIPTION_ID}}"

  azure:creds:
    deps:
      - task: azure:init
        silent: true
    preconditions:
      - yq 'true' config.yaml
    cmds:
      - task: azure:creds:create
      - task: azure:creds:get

  azure:creds:get:
    deps:
      - task: azure:init
        silent: true
    preconditions:
      - yq 'true' config.yaml
    vars:
      IDENTITY_NAME: crossplane
      SUBSCRIPTION_ID:
        sh: yq '.subscription' config.yaml
      RESOURCE_GROUP:
        sh: yq '.resource_group' config.yaml
      CLIENT_ID:
        sh: az identity show --resource-group "{{.RESOURCE_GROUP}}" --name {{.IDENTITY_NAME}} --query "clientId" --output tsv --only-show-errors
      TENANT_ID:
        sh: az identity show --resource-group "{{.RESOURCE_GROUP}}" --name {{.IDENTITY_NAME}} --query "tenantId" --output tsv --only-show-errors
    cmds:
      - task: update:config
        vars:
          RUN: yq -i e '.crossplane_workload_identity |= { .clientId |= "{{.CLIENT_ID}}" | .tenantId |= "{{.TENANT_ID}}"}' config.yaml

  azure:creds:create:
    deps:
      - task: azure:init
        silent: true
    preconditions:
      - yq 'true' config.yaml
    vars:
      IDENTITY_NAME: crossplane
      IDENTITY_NAMESPACE: crossplane-system
      SUBSCRIPTION_ID:
        sh: yq '.subscription' config.yaml
      RESOURCE_GROUP:
        sh: yq '.resource_group' config.yaml
      OIDC_ISSUER:
        sh: yq '.cluster_oidc_issuer_url' config.yaml
    sources:
      - config.yaml
    cmds:
      - task: if
        vars:
          IF: $(az identity list --resource-group "{{.RESOURCE_GROUP}}" --only-show-errors -o yaml | yq '[.[] | select(.name=="{{.IDENTITY_NAME}}")] | length') -eq 0
          RUN: az identity create --name "{{.IDENTITY_NAME}}" --resource-group "{{.RESOURCE_GROUP}}" --only-show-errors --output none
      - |
        az identity federated-credential update \
          --name "{{.IDENTITY_NAME}}_fc" \
          --identity-name "{{.IDENTITY_NAME}}" \
          --resource-group "{{.RESOURCE_GROUP}}" \
          --issuer "{{.OIDC_ISSUER}}" \
          --subject "system:serviceaccount:{{.IDENTITY_NAMESPACE}}:{{.IDENTITY_NAME}}" \
          --audience "api://AzureADTokenExchange" \
          --only-show-errors --output none 2>/dev/null || \
        az identity federated-credential create \
          --name "{{.IDENTITY_NAME}}_fc" \
          --identity-name "{{.IDENTITY_NAME}}" \
          --resource-group "{{.RESOURCE_GROUP}}" \
          --issuer "{{.OIDC_ISSUER}}" \
          --subject "system:serviceaccount:{{.IDENTITY_NAMESPACE}}:{{.IDENTITY_NAME}}" \
          --audience "api://AzureADTokenExchange" \
          --only-show-errors --output none
      - task: wait
        vars:
          TIMEOUT: 10
          IF: true
      - |-
        az role assignment create \
          --assignee-object-id "$(az identity show --resource-group {{.RESOURCE_GROUP}} --name {{.IDENTITY_NAME}} --query 'principalId' -o tsv --only-show-errors)" \
          --role "Owner" \
          --scope "/subscriptions/{{.SUBSCRIPTION_ID}}/resourceGroups/{{.RESOURCE_GROUP}}" \
          --only-show-errors \
          --output none

  azure:creds:delete:
    deps:
      - task: azure:init
        silent: true
    preconditions:
      - yq 'true' config.yaml
    vars:
      IDENTITY_NAME: crossplane
      SUBSCRIPTION_ID:
        sh: yq '.subscription' config.yaml
      RESOURCE_GROUP:
        sh: yq '.resource_group' config.yaml
      PRINCIPAL_ID:
        sh: az identity show --resource-group {{.RESOURCE_GROUP}} --name {{.IDENTITY_NAME}} --query 'principalId' -o tsv --only-show-errors
      ROLE_ASSIGNMENT_ID:
        sh: az role assignment list --resource-group {{.RESOURCE_GROUP}} --query "[?principalId=='{{.PRINCIPAL_ID}}'].id" -o tsv --only-show-errors
    cmds:
      - az role assignment delete --ids {{.ROLE_ASSIGNMENT_ID}}
      - az identity delete --name "{{.IDENTITY_NAME}}" --resource-group "{{.RESOURCE_GROUP}}" --subscription "{{.SUBSCRIPTION_ID}}" --only-show-errors --output none

  cleanup:
    internal: true
    cmds:
      - cmd: rm -f "{{.KUBECONFIG}}"
        ignore_error: true

  wait:
    internal: true
    env:
      WAIT_TIMEOUT: "{{default 300 .TIMEOUT}}"
    cmds:
      - while [[ {{.IF}} ]] && [[ ${WAIT_TIMEOUT} -gt 0 ]]; do sleep 5 && ((WAIT_TIMEOUT-=5)); done || exit 1

  if:
    internal: true
    cmds:
      - if [[ {{.IF}} ]]; then {{.RUN}}; fi || exit 1

  ifelse:
    internal: true
    cmds:
      - if [[ {{.IF}} ]]; then {{.IF_RUN}}; else {{.ELSE_RUN}}; fi || exit 1

  uninstall:
    deps:
      - update:kubeconfig
    cmds:
      - defer: { task: cleanup }
      - kubectl delete ingress -A --all --interactive=false --now
      - kubectl delete workloadidentities.azure.livewyer.io -A --all --interactive=false --now
      - task: wait
        vars:
          IF: true
          TIMEOUT: 30
      - kubectl delete pkg --all --interactive=false --now
      - task: azure:creds:delete
      - kubectl delete appset -A --all --interactive=false --now
      - kubectl delete app -A --all --interactive=false --now --cascade=orphan
      - task: wait
        vars:
          IF: true
          TIMEOUT: 30
      - task: helmfile:destroy
      - cmd: kubectl delete ns {{.ITEM}} --interactive=false --now --cascade=orphan
        for: { var: NS }
    vars:
      NS:
        sh: yq 'to_entries[] | select(.value.enabled==true).value.namespace' packages/addons/values.yaml
    ignore_error: true

  test:aks:create:
    deps:
      - task: azure:init
        silent: true
    env:
      KUBECONFIG:
        sh: echo ${HOME}/.kube/config
    preconditions:
      - yq 'true' config.yaml
    cmds:
      - |
        az aks create \
          --name $(yq '.cluster_name' config.yaml) \
          --location $(yq '.location' config.yaml) \
          --resource-group $(yq '.resource_group' config.yaml) \
          --kubernetes-version ${AKS_VERSION:-1.33} \
          --sku base \
          --enable-oidc-issuer \
          --enable-workload-identity \
          --node-vm-size ${AKS_NODE_SIZE:-standard_d4alds_v6} \
          --output none {{.CLI_ARGS}}
      - az aks get-credentials --name $(yq '.cluster_name' config.yaml) --resource-group $(yq '.resource_group' config.yaml) --overwrite-existing --only-show-errors
      - task: test:config:update
        vars:
          OIDC_ISSUER:
            sh: az aks show --name $(yq '.cluster_name' config.yaml) --resource-group $(yq '.resource_group' config.yaml) --query "oidcIssuerProfile.issuerUrl" -o tsv --only-show-errors

  test:config:update:
    preconditions:
      - yq 'true' config.yaml
    cmds:
      - yq -i e '.cluster_oidc_issuer_url |= "{{.OIDC_ISSUER}}"' config.yaml

  test:aks:destroy:
    deps:
      - task: azure:init
        silent: true
    preconditions:
      - yq 'true' config.yaml
    cmds:
      - az aks delete --name $(yq '.cluster_name' config.yaml) --resource-group $(yq '.resource_group' config.yaml) --yes {{.CLI_ARGS}}

  helmfile:
    cmds:
      - task: helmfile:init
      - task: helmfile:apply
  helmfile:init:
    cmds:
      - helmfile init {{.CLI_ARGS}}
  helmfile:lint:
    cmds:
      - helmfile lint {{.CLI_ARGS}}
  helmfile:diff:
    cmds:
      - helmfile diff {{.CLI_ARGS}}
  helmfile:build:
    cmds:
      - helmfile build {{.CLI_ARGS}}
  helmfile:apply:
    cmds:
      - helmfile apply {{.CLI_ARGS}}
  helmfile:list:
    cmds:
      - helmfile list {{.CLI_ARGS}}
  helmfile:status:
    cmds:
      - helmfile status {{.CLI_ARGS}}
  helmfile:template:
    cmds:
      - helmfile template {{.CLI_ARGS}}
  helmfile:deps:
    cmds:
      - helmfile deps {{.CLI_ARGS}}
  helmfile:sync:
    cmds:
      - helmfile sync {{.CLI_ARGS}}
  helmfile:destroy:
    cmds:
      - helmfile destroy {{.CLI_ARGS}}
