# https://taskfile.dev

version: "3"

vars:
  REPO_ROOT:
    sh: git rev-parse --show-toplevel

tasks:
  init:
    cmds:
      - task: helmfile:init
      - task: helmfile:lint
      - task: helmfile:build
  install:
    cmds:
      - task: helmfile:apply
  update:
    cmds:
      - task: helmfile:sync
  uninstall:
    cmds:
      - task: helmfile:destroy

  helmfile:init:
    cmds:
      - REPO_ROOT="{{.REPO_ROOT}}" helmfile init {{.CLI_ARGS}}
  helmfile:lint:
    cmds:
      - REPO_ROOT="{{.REPO_ROOT}}" helmfile lint {{.CLI_ARGS}}
  helmfile:diff:
    cmds:
      - REPO_ROOT="{{.REPO_ROOT}}" helmfile diff {{.CLI_ARGS}}
  helmfile:build:
    cmds:
      - REPO_ROOT="{{.REPO_ROOT}}" helmfile build {{.CLI_ARGS}}
  helmfile:apply:
    cmds:
      - REPO_ROOT="{{.REPO_ROOT}}" helmfile apply {{.CLI_ARGS}}
  helmfile:list:
    cmds:
      - REPO_ROOT="{{.REPO_ROOT}}" helmfile list {{.CLI_ARGS}}
  helmfile:status:
    cmds:
      - REPO_ROOT="{{.REPO_ROOT}}" helmfile status {{.CLI_ARGS}}
  helmfile:template:
    cmds:
      - REPO_ROOT="{{.REPO_ROOT}}" helmfile template {{.CLI_ARGS}}
  helmfile:deps:
    cmds:
      - REPO_ROOT="{{.REPO_ROOT}}" helmfile deps {{.CLI_ARGS}}
  helmfile:sync:
    cmds:
      - REPO_ROOT="{{.REPO_ROOT}}" helmfile sync {{.CLI_ARGS}}
  helmfile:destroy:
    cmds:
      - REPO_ROOT="{{.REPO_ROOT}}" helmfile destroy {{.CLI_ARGS}}
