apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: keycloak
  namespace: keycloak
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      serviceAccountRef:
        name: ${SA_NAME}
      vaultUrl: ${VAULT_URL}
