apiVersion: azure.livewyer.io/v1alpha1
kind: WorkloadIdentity
metadata:
  name: keycloak
  namespace: keycloak
spec:
  forProvider:
    location: "{{ .location }}"
    oidcIssuerURL: "{{ .clusterOIDCIssuerURL }}"
    resourceGroupName: "{{ .resourceGroup }}"
    roleAssignments:
      - roleDefinitionName: Key Vault Secrets User
        scope: "{{ .subscription }}"
      - roleDefinitionName: Key Vault Reader
        scope: "{{ .subscription }}"
    serviceAccountName: external-secret-keycloak
