apiVersion: azure.livewyer.io/v1alpha1
kind: WorkloadIdentity
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  forProvider:
    location: "{{ .metadata.annotations.location }}"
    oidcIssuerURL: "{{ .metadata.annotations.clusterOIDCIssuerURL }}"
    resourceGroupName: "{{ .metadata.annotations.resourceGroup }}"
    roleAssignments:
      - roleDefinitionName: Key Vault Secrets User
        scope: "{{ .metadata.annotations.subscription }}/resourcegroups/resource-{{ .metadata.annotations.resourceGroup }}"
    serviceAccountName: external-secrets
