apiVersion: azure.livewyer.io/v1alpha1
kind: WorkloadIdentity
metadata:
  name: external-dns
  namespace: external-dns
spec:
  forProvider:
    location: "{{ .metadata.annotations.location }}"
    oidcIssuerURL: "{{ .metadata.annotations.clusterOIDCIssuerURL }}"
    resourceGroupName: "{{ .metadata.annotations.resourceGroup }}"
    roleAssignments:
      - roleDefinitionName: DNS Zone Contributor
        scope: "{{ .metadata.annotations.resourceGroup }}"
      - roleDefinitionName: Reader
        scope: "{{ .metadata.annotations.resourceGroup }}"
    serviceAccountName: external-dns
