apiVersion: azure.livewyer.io/v1alpha1
kind: WorkloadIdentity
metadata:
  name: keycloak
  namespace: keycloak
spec:
  forProvider:
    location: "{{ .metadata.annotations.location }}"
    oidcIssuerURL: "{{ .metadata.annotations.clusterOIDCIssuerURL }}"
    resourceGroupName: "{{ .metadata.annotations.resourceGroup }}"
    roleAssignments:
      - roleDefinitionName: Key Vault Secrets User
        scope: "{{ .metadata.annotations.resourceGroup }}"
      - roleDefinitionName: Key Vault Reader
        scope: "{{ .metadata.annotations.resourceGroup }}"
    serviceAccountName: external-secret-keycloak
