installCRDs: true
global:
  leaderElection:
    namespace: cert-manager
webhook:
  validatingWebhookConfiguration:
    namespaceSelector:
      matchExpressions:
        - key: cert-manager.io/disable-validation
          operator: NotIn
          values:
            - "true"
        - key: name
          operator: NotIn
          values:
            - cert-manager
        - key: control-plane
          operator: NotIn
          values:
            - "true"
        - key: kubernetes.azure.com/managedby
          operator: NotIn
          values:
            - aks
